const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const pageDir = path.resolve(__dirname, "../pages/index");

test("home feed refresh uses restrained medium haptics", () => {
  const indexJs = fs.readFileSync(path.join(pageDir, "index.js"), "utf8");
  const indexJson = JSON.parse(fs.readFileSync(path.join(pageDir, "index.json"), "utf8"));
  const indexWxml = fs.readFileSync(path.join(pageDir, "index.wxml"), "utf8");
  const hapticsJs = fs.readFileSync(path.resolve(__dirname, "../utils/haptics.js"), "utf8");
  const savedJs = fs.readFileSync(path.resolve(__dirname, "../pages/saved/saved.js"), "utf8");
  const aboutJs = fs.readFileSync(path.resolve(__dirname, "../pages/about/about.js"), "utf8");
  const aboutWxml = fs.readFileSync(path.resolve(__dirname, "../pages/about/about.wxml"), "utf8");
  const aboutWxss = fs.readFileSync(path.resolve(__dirname, "../pages/about/about.wxss"), "utf8");
  const appJs = fs.readFileSync(path.resolve(__dirname, "../app.js"), "utf8");

  assert.equal(indexJson.enablePullDownRefresh, true);
  assert.match(hapticsJs, /vibrateShort\(\{\s*type:\s*safeType\s*\}\)/);
  assert.match(hapticsJs, /defaultType:\s*"medium"/);
  assert.match(hapticsJs, /refreshInterval:\s*320/);
  assert.match(hapticsJs, /tabInterval:\s*220/);
  assert.match(hapticsJs, /SCROLL_HAPTIC_PROFILE/);
  assert.match(hapticsJs, /minInterval:\s*145/);
  assert.doesNotMatch(hapticsJs, /minInterval:\s*130/);
  assert.match(hapticsJs, /poster:\s*\{\s*\.\.\.SCROLL_HAPTIC_PROFILE\s*\}/);
  assert.match(hapticsJs, /feed:\s*\{\s*\.\.\.SCROLL_HAPTIC_PROFILE\s*\}/);
  assert.match(indexJs, /lightHaptic\(intervalMs = HAPTIC\.refreshInterval\)/);
  assert.match(indexJs, /now - this\.lastHapticAt < intervalMs/);
  assert.match(indexJs, /suppressFeedHaptic\(ms = 700\)/);
  assert.match(indexJs, /now < this\.ignoreFeedHapticUntil/);
  assert.match(indexJs, /onPullDownRefresh\(\)/);
  assert.match(indexJs, /onPosterStripScroll\(event\)/);
  assert.match(indexJs, /onPageScroll\(event\)/);
  assert.match(indexJs, /nextScrollHaptic\(this\.posterHapticState, scrollLeft/);
  assert.match(indexJs, /nextScrollHaptic\(this\.feedHapticState, scrollTop/);
  assert.match(indexJs, /onTabItemTap\(\)/);
  assert.match(savedJs, /onTabItemTap\(\)/);
  assert.match(aboutJs, /onTabItemTap\(\)/);
  assert.match(appJs, /showTabBarRedDot/);
  assert.match(appJs, /weeklySoundAtlasNoticeSeen:v1/);
  assert.match(aboutJs, /hideTabBarRedDot\(\{\s*index:\s*ABOUT_TAB_INDEX\s*\}\)/);
  assert.match(indexWxml, /bindscroll="onPosterStripScroll"/);
  assert.match(indexWxml, /bindtap="retryLoadData"/);
  assert.match(indexWxml, /loadingHint/);
  assert.match(indexWxml, /errorHint/);
});

test("home feed loading keeps one active request and queues retries", () => {
  const indexJs = fs.readFileSync(path.join(pageDir, "index.js"), "utf8");
  const appJs = fs.readFileSync(path.resolve(__dirname, "../app.js"), "utf8");
  const apiJs = fs.readFileSync(path.resolve(__dirname, "../utils/api.js"), "utf8");
  const i18nJs = fs.readFileSync(path.resolve(__dirname, "../utils/i18n.js"), "utf8");

  assert.match(appJs, /publicFallbackDelayMs:\s*250/);
  assert.match(appJs, /publicRequestTimeoutMs:\s*3000/);
  assert.match(appJs, /cacheFallbackDelayMs:\s*2200/);
  const snapshotDelayMatch = appJs.match(/offlineSnapshotFallbackDelayMs:\s*(-?\d+)/);
  assert.ok(snapshotDelayMatch, "offline snapshot fallback delay must be configured");
  assert.ok(Number(snapshotDelayMatch[1]) < 0, "offline snapshot must not race the default current feed");
  assert.match(appJs, /offlineSnapshotFallback:\s*true/);
  assert.match(appJs, /fastOfflineSnapshotFallback:\s*false/);
  assert.match(apiJs, /requestContainerOrFallback/);
  assert.match(apiJs, /setTimeout\(startFallback,\s*delayMs\)/);
  assert.match(apiJs, /setTimeout\(startFastSnapshot,\s*snapshotDelayMs\)/);
  assert.match(apiJs, /shouldBypassStoredRead\(data\)/);
  assert.match(apiJs, /shouldSkipStoredWrite\(data\)/);
  assert.match(apiJs, /shouldRequireLiveResponse\(data\)/);
  assert.match(apiJs, /const inflightRequests = new Map\(\)/);
  assert.match(apiJs, /buildInflightKey\(path, data\)/);
  assert.match(apiJs, /if \(existing\) return existing/);
  assert.match(indexJs, /isLoadingRequest:\s*false/);
  assert.match(indexJs, /pendingLoadOptions:\s*null/);
  assert.match(indexJs, /loadSeq:\s*0/);
  assert.match(indexJs, /backgroundRefreshTimer:\s*null/);
  assert.match(indexJs, /backgroundRefreshAttempts:\s*0/);
  assert.match(indexJs, /LOAD_HINT_SCHEDULE/);
  assert.match(indexJs, /MAX_SILENT_LOAD_RETRIES/);
  assert.match(indexJs, /text\("index", lang\)/);
  assert.match(i18nJs, /loadingStart:\s*"正在连接活动源"/);
  assert.match(i18nJs, /loadingConnectingHint:\s*"网络较慢时会自动切换备用通道，请保持页面打开。"/);
  assert.match(i18nJs, /loadingFallback:\s*"后台刷新中"/);
  assert.match(i18nJs, /retryBusy:\s*"正在连接活动源，请稍等"/);
  assert.match(i18nJs, /高清设备图/);
  assert.match(i18nJs, /Beta 版仅用于早期体验和信息核对/);
  assert.match(i18nJs, /人工确认/);
  assert.match(i18nJs, /priority/);
  assert.match(indexJs, /if \(this\.isLoadingRequest\)/);
  assert.match(indexJs, /this\.showBusyToast\(\)/);
  assert.match(indexJs, /return \{ skipped:\s*true \}/);
  assert.match(indexJs, /const selectedCityKey = opts\.cityKey !== undefined \? opts\.cityKey : this\.data\.selectedCity/);
  assert.match(indexJs, /const dateSelection = pageDateSelection\(this\.data, opts\)/);
  assert.match(indexJs, /const dateQuery = dateSelectionQuery\(dateSelection\)/);
  assert.match(indexJs, /requestApi\("\/api\/v1\/weekly\/manifest",\s*\{\s*__skipCache:\s*true,\s*__liveOnly:\s*true\s*\}\)/);
  assert.match(indexJs, /currentFeedBehindManifest\(manifest,\s*current\)/);
  assert.match(indexJs, /const currentFetchOptions = \{\s*cityKey:\s*"",\s*date:\s*"",\s*lookbackDays:\s*0,\s*loadSeq,\s*skipCache:\s*opts\.skipCache === true,\s*liveOnly:\s*opts\.liveOnly === true,\s*liveRefresh:\s*backgroundRefresh \|\| opts\.liveRefresh === true,\s*\}/s);
  assert.match(i18nJs, /loadingRefreshing:\s*"正在同步最新活动包"/);
  assert.match(i18nJs, /loadingRefreshingHint:\s*"检测到活动包已更新，先同步新数据，避免显示旧活动。"/);
  assert.match(indexJs, /skipCache:\s*true/);
  assert.match(indexJs, /liveOnly:\s*true/);
  assert.match(indexJs, /const facetUniverse = filterItemsByDateSelection\(filterSourceItems, dateSelection\)/);
  assert.match(indexJs, /const displayItems = filterItemsByCityKey\(facetUniverse, resolvedCityKey\)/);
  assert.match(indexJs, /setLoadingProgress\(progress, step, loadSeq, hint\)/);
  assert.match(indexJs, /loadSeq && loadSeq !== this\.loadSeq/);
  assert.match(indexJs, /scheduleLoadingHints\(labels, loadSeq\)/);
  assert.match(indexJs, /scheduleBackgroundRefresh\(\)/);
  assert.match(indexJs, /clearBackgroundRefreshTimer\(\)/);
  assert.match(indexJs, /backgroundRefresh:\s*true/);
  assert.match(indexJs, /silentRetryCount/);
  assert.match(indexJs, /LOAD_RETRY_DELAYS_MS/);
  assert.match(indexJs, /if \(!this\.destroyed && loadSeq === this\.loadSeq\) this\.loadData\(retryOptions\)/);
});
