const assert = require("node:assert/strict");
const childProcess = require("node:child_process");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const searchEvents = require("../ai_packages/weekly/weekly-events-skill/apis/searchEvents");
const { weekendDateSelection } = require("../services/homeFilters");

const CURRENT_WEEKEND = {
  mode: "this_weekend",
  exactDate: "",
  startKey: "2026-07-17",
  endKey: "2026-07-19",
};

test("independent AI package business-date module is generated byte-for-byte from canonical", () => {
  const canonicalPath = path.resolve(__dirname, "../utils/businessDate.js");
  const generatedPath = path.resolve(__dirname, "../ai_packages/weekly/shared/businessDate.js");
  const searchEventsPath = path.resolve(__dirname, "../ai_packages/weekly/weekly-events-skill/apis/searchEvents.js");
  assert.equal(fs.existsSync(generatedPath), true, "regenerate the independent-package copy from utils/businessDate.js");
  assert.equal(fs.readFileSync(generatedPath, "utf8"), fs.readFileSync(canonicalPath, "utf8"));
  const searchEventsSource = fs.readFileSync(searchEventsPath, "utf8");
  assert.match(searchEventsSource, /require\("\.\.\/\.\.\/shared\/businessDate"\)/);
  assert.doesNotMatch(searchEventsSource, /require\([^)]*utils\/businessDate/);
});

test("home and AI weekend selection keep the current Shanghai week on Sunday", () => {
  const sundayShanghai = new Date("2026-07-19T05:29:00.000Z");

  assert.deepEqual(weekendDateSelection(0, sundayShanghai), CURRENT_WEEKEND);
  assert.deepEqual(
    searchEvents._private.resolveDateRange({ timeHint: "weekend" }, sundayShanghai),
    { dateFrom: "2026-07-17", dateTo: "2026-07-19" },
  );
  assert.deepEqual(
    searchEvents._private.resolveDateRange({ timeHint: "weekend", referenceDate: "2026-07-19" }, sundayShanghai),
    { dateFrom: "2026-07-17", dateTo: "2026-07-19" },
  );
});

test("home and AI weekend selection keep Sunday business date until 07:00 Shanghai Monday", () => {
  const mondayBeforeCutoffShanghai = new Date("2026-07-19T18:00:00.000Z");

  assert.deepEqual(weekendDateSelection(0, mondayBeforeCutoffShanghai), CURRENT_WEEKEND);
  assert.deepEqual(
    searchEvents._private.resolveDateRange({ timeHint: "weekend" }, mondayBeforeCutoffShanghai),
    { dateFrom: "2026-07-17", dateTo: "2026-07-19" },
  );
});

test("home and AI weekend selection advance together after 07:00 Shanghai Monday", () => {
  const mondayAfterCutoffShanghai = new Date("2026-07-19T23:00:00.000Z");

  assert.deepEqual(weekendDateSelection(0, mondayAfterCutoffShanghai), {
    mode: "this_weekend",
    exactDate: "",
    startKey: "2026-07-24",
    endKey: "2026-07-26",
  });
  assert.deepEqual(
    searchEvents._private.resolveDateRange({ timeHint: "weekend" }, mondayAfterCutoffShanghai),
    { dateFrom: "2026-07-24", dateTo: "2026-07-26" },
  );
});

test("weekend selection is invariant across device time zones", () => {
  const appRoot = path.resolve(__dirname, "..");
  const script = [
    `const home = require(${JSON.stringify(path.join(appRoot, "services/homeFilters.js"))});`,
    `const ai = require(${JSON.stringify(path.join(appRoot, "ai_packages/weekly/weekly-events-skill/apis/searchEvents.js"))});`,
    'const now = new Date("2026-07-19T18:00:00.000Z");',
    "process.stdout.write(JSON.stringify({ home: home.weekendDateSelection(0, now), ai: ai._private.resolveDateRange({ timeHint: 'weekend' }, now) }));",
  ].join("");

  for (const timezone of ["UTC", "America/Los_Angeles", "Asia/Shanghai"]) {
    const result = JSON.parse(childProcess.execFileSync(process.execPath, ["-e", script], {
      encoding: "utf8",
      env: { ...process.env, TZ: timezone },
    }));
    assert.deepEqual(result.home, CURRENT_WEEKEND, timezone);
    assert.deepEqual(result.ai, { dateFrom: "2026-07-17", dateTo: "2026-07-19" }, timezone);
  }
});
